paths:
    /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos OK desde la DB
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Lista de productos"
                  productos:
                    type: array
                    items:
                      $ref: '#components/schemas/Products'
        # "500":
        #   description: Error interno del servidor
    post:
      summary: Graba un nuevo producto
      tags:
        - Products
      responses:
        "201":
          description: Producto creado
        "500":
          description: Error interno del servidor
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado de mongo
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido...    
        email:
          type: string
          description: Correo electronico
        password: 
          type: string
          description: contraseña de acceso  
      example:
        _id: ObjectId("60acc54545c8e82e0475f73a")
        first_name: Diego
        last_name: Polverelli
        email: diegopolverelli@hotmail.com
        password: "123"
    Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado de mongo
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: Codigo del producto    
      example:
        _id: ObjectId("60acc54545c8e82e0475f73a")
        description: Martillo
        code: A0324z
  requestBodies:
    createUser:
      type: object
      properties:
        first_name:
          type: string
          description: Nombre de usurio
        last_name:
          type: string
          description: Apellido
        email:
          type: string
          description: Correo del usuario
        password:
          type: string
          description: Contraseña del usuario
      example:
        first_name: Diego
        last_name: Polverelli
        email: diego@hotmail.com
        password: coder123        